service: cipherSchools
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-south-1
  timeout: 10

functions:
  api:
    handler: src/server.handler
    events:
      - http: ANY /{proxy+}
      - http: ANY /

    environment:
      DB_URL: ${env:DB_URL}

plugins:
  - serverless-plugin-typescript
